[workspace]
resolver = "2"
members = ["sys", "lib"]

[workspace.package]
version = "0.4.2+0.16.11"
authors = ["Daria Sukhonina <dariasukhonina@gmail.com>"]
rust-version = "1.78"
repository = "https://github.com/ZetaNumbers/tigerbeetle-rs"
license = "MIT OR Apache-2.0"
